
services:
  mariadb:
    build:
      context: ./requirements/mariadb
    container_name: mariadb
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_USER=${MYSQL_USER}     
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
    restart: always
    env_file: .env
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - inception
    healthcheck:
      test: [
        "CMD-SHELL",
        "mysqladmin ping -h 127.0.0.1 -u${MYSQL_USER} -p${MYSQL_PASSWORD}"
      ]
      interval: 10s
      timeout: 10s
      retries: 20

  wordpress:
    build:
      context: ./requirements/wordpress
    container_name: wordpress
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_USER=${MYSQL_USER}     
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - WORDPRESS_TITLE=${WORDPRESS_TITLE}
      - WORDPRESS_ADMIN=${WORDPRESS_ADMIN}
      - WORDPRESS_ADMIN_PASSWORD=${WORDPRESS_ADMIN_PASSWORD}
      - WORDPRESS_ADMIN_EMAIL=${WORDPRESS_ADMIN_EMAIL}
      - WORDPRESS_OTHER=${WORDPRESS_OTHER}
      - WORDPRESS_OTHER_PASSWORD=${WORDPRESS_OTHER_PASSWORD}
      - WORDPRESS_OTHER_EMAIL=${WORDPRESS_OTHER_EMAIL}
      - DOMAIN_NAME=${DOMAIN_NAME}
    restart: always
    env_file: .env
    volumes:
      - wordpress_data:/var/www/html
    networks:
      - inception
    depends_on:
      mariadb:
        condition: service_healthy

  nginx:
    build:
      context: ./requirements/nginx
    container_name: nginx
    restart: always
    env_file: .env
    depends_on:
      - wordpress
    volumes:
      - wordpress_data:/var/www/html
    ports:
      - "443:443"
    networks:
      - inception

volumes:
  mariadb-data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/eagbomei/data/mariadb
  wordpress-data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/eagbomei/data/wordpress

networks:
  inception:
    driver: bridge