# srcs/docker-compose.yml
# mariaDB stuff
version: '3.8'

services:
  mariadb:
    build:
      context: ./requirements/mariadb
    container_name: mariadb
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_USER=${MYSQL_USER}     
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
    restart: always
    env_file: .env
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - inception

  wordpress:
    build:
      context: ./requirements/wordpress
    container_name: wordpress
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_USER=${MYSQL_USER}     
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - WORDPRESS_TITLE=${WORDPRESS_TITLE}
      - WORDPRESS_ADMIN=${WORDPRESS_ADMIN}
      - WORDPRESS_ADMIN_PASSWORD=${WORDPRESS_ADMIN_PASSWORD}
      - WORDPRESS_ADMIN_EMAIL=${WORDPRESS_ADMIN_EMAIL}
      - WORDPRESS_OTHER=${WORDPRESS_OTHER}
      - WORDPRESS_OTHER_PASSWORD=${WORDPRESS_OTHER_PASSWORD}
      - WORDPRESS_OTHER_EMAIL=${WORDPRESS_OTHER_EMAIL}
      - DOMAIN_NAME=${DOMAIN_NAME}
    restart: always
    env_file: .env
    depends_on:
      - mariadb
    volumes:
      - wordpress_data:/var/www/wordpress
    networks:
      - inception

  nginx:
    build:
      context: ./requirements/nginx
    container_name: nginx
    restart: always
    env_file: .env
    depends_on:
      - wordpress
    volumes:
      - wordpress_data:/var/www/wordpress
    ports:
      - "443:443"
    networks:
      - inception

volumes:
  mariadb_data:
    driver: local
    name: mariadb_data
  wordpress_data:
    driver: local
    name: wordpress_data

networks:
  inception:
    driver: bridge