# srcs/docker-compose.yml
# mariaDB stuff
version: '3.8'

services:
  mariadb:
    build:
      context: ./requirements/mariadb
    container_name: mariadb
    restart: always
    env_file: .env
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - inception

volumes:
  mariadb_data:
    driver: local
    name: mariadb_data

networks:
  inception:
    driver: bridge